//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificentrosFormatos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas
    {
        public int idLinea { get; set; }
        public string numeroCentro { get; set; }
        public int numero { get; set; }
        public string combustible { get; set; }
        public string tipo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public int idUsuarioAlta { get; set; }
    }
}
