//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificentrosFormatos.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerificentrosDB : DbContext
    {
        public VerificentrosDB()
            : base("name=VerificentrosDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dinamometros> Dinamometros { get; set; }
        public virtual DbSet<Gabinetes> Gabinetes { get; set; }
        public virtual DbSet<Lineas> Lineas { get; set; }
        public virtual DbSet<Microbancas> Microbancas { get; set; }
        public virtual DbSet<Opacimetros> Opacimetros { get; set; }
        public virtual DbSet<RepresentantesLegales> RepresentantesLegales { get; set; }
        public virtual DbSet<Tacometros> Tacometros { get; set; }
        public virtual DbSet<Verificentros> Verificentros { get; set; }
    }
}
